project_id = "wepsgnqxykzcynsyfomk"

[functions.fire-trigger]
verify_jwt = false

[functions.ai-predict]
verify_jwt = false

[functions.weather-poll]
verify_jwt = false

[functions.calculate-premium]
verify_jwt = false
